apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-roboshop"
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c

  containers:
  - name: nginx
    image: nginx
    volumeMounts: #dockerrun -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic

apiVersion: v1
kind: Service
metadata: 
  name: efs-dynamic
  labels: 
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 #serviceport
      targetPort: 80 #containerport