apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: gcr.io/google-samples/hello-app:2.0
    env:
    - name: Course
      value: "kubernetes"
    - name: Trainer
      value: "sivakumar"
