apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  #replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
    app: nginx 
spec:
  replicas: 3
  #these are the labels replicaset uses to create pod replicas this should mach pod labels
  selector:
    matchLabels:
      purpose: rs-demo
      project: roboshop
      app: nginx 

  #pod definition
  template:
      metadata:
        labels:
          purpose: rs-demo
          project: roboshop
          app: nginx 
      spec:
        containers:
        - name: nginx
          image: nginx